[package]
name = "villa"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
env_logger = "0.10.0"
glam = "0.24.0"
image = "0.24.6"
pollster = "0.3.0"
wgpu = "0.18.0"
winit = "0.28.6"
