#ifndef VKAD_WINDOW_WIN32_KEYS_H_
#define VKAD_WINDOW_WIN32_KEYS_H_

#define VKAD_KEY_SHIFT 0x10
#define VKAD_KEY_SPACE 0x20
#define VKAD_KEY_A 0x41
#define VKAD_KEY_C 0x43
#define VKAD_KEY_D 0x44
#define VKAD_KEY_E 0x45
#define VKAD_KEY_P 0x50
#define VKAD_KEY_S 0x53
#define VKAD_KEY_Q 0x51
#define VKAD_KEY_W 0x57
#define VKAD_KEY_ESC 0x1B

#endif // !VKAD_WINDOW_WIN32_KEYS_H_
